apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secret
type: Opaque
stringData:
  postgres-password: {{ .Values.secret.postgresPassword | quote }}
  jwt-secret: {{ .Values.secret.jwtSecret | quote }}
  football-api-key: {{ .Values.secret.footballApiKey | quote }}
  groq-api-key: {{ .Values.secret.groqApiKey | quote }}
  google-client-id: {{ .Values.secret.googleClientId | quote }}
  google-client-secret: {{ .Values.secret.googleClientSecret | quote }}
